theme: jekyll-theme-cayman
title: zmcNotafraid's Blog
description: >- # this means tj:qgnore newlines until "baseurl:"
  记录过程，分享你我
markdown: kramdown
timezone:	"Asia/Shanghai"
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar
